Added Imgchecker and fixed images
fossasia/gci15.fossasia.org pull request #741
Opened 2016-12-16 11:10 UTC by ankitrgadiya

Fixed Partially. #738 
* Added Imgchecker.rb By Abishek V Ashok.
* Added script in .travis.yml
* Added gem 'fastimage' used in Imgchecker.rb
* Fixed Photos accordingly.

####### Note: In Imgchecker, I've commented out Gallery section as it's giving errors. Need help with that.

2016-12-17 10:59 UTC, abishekvashok requested changes
Change the directory names and the images sizes this site has varieties...

2016-12-17 11:44 UTC, Abhi2424shek commented
@ankitrgadiya fixed it @niccokunzmann @jig08 @hemantjadon we are ready to go, shall i rebase it or some one among you shall.

2016-12-17 11:51 UTC, ankitrgadiya commented
@Abhi2424shek I did. I'm no longer afraid of rebase

2016-12-17 11:52 UTC, Abhi2424shek commented
@ankitrgadiya sure I was'nt on PC to rebase.

2016-12-17 11:52 UTC, ankitrgadiya commented
@Abhi2424shek ah okay no problem. And Thanks bro for helping me.

2016-12-17 11:53 UTC, ankitrgadiya commented
Fixed #738 #671

2016-12-17 13:29 UTC, Abhi2424shek commented
Sure bro  will always be there, when you need me, so
keep calm and expect me

2016-12-17 13:31 UTC, Abhi2424shek commented
Update the pr body see the bold ones 😉

2016-12-17 19:03 UTC, robbyoconnor commented on scripts/ImgChecker/ImgChecker.rb
> +blogsImgSize = 240
Why 240x240 for blogs? Those aren't square...

2016-12-17 19:06 UTC, robbyoconnor commented on scripts/ImgChecker/ImgChecker.rb
> +blogsImgSize = 240
Assuming you mean blog screenshots...

2016-12-18 06:15 UTC, Abhi2424shek commented on scripts/ImgChecker/ImgChecker.rb
> +blogsImgSize = 240
Please check the current size in the repo sir, and the site it uses cards of 240x240 px

2016-12-18 08:52 UTC, ankitrgadiya commented on scripts/ImgChecker/ImgChecker.rb
> +blogsImgSize = 240
@robbyoconnor All images for Blog Posts are 240x240 and that's why [tests](https://travis-ci.org/fossasia/gci15.fossasia.org/builds/184755491) are passing. :-)

2016-12-18 09:15 UTC, robbyoconnor commented on scripts/ImgChecker/ImgChecker.rb
> +blogsImgSize = 240
Good work

2016-12-18 09:16 UTC, robbyoconnor approved these changes
LGTM.

2016-12-18 09:22 UTC, Abhi2424shek commented
@robbyoconnor then merge it sir!

2016-12-18 10:38 UTC, robbyoconnor commented
I'm gonna merge this -- but will probably refactor the Image Checker script.

2016-12-18 10:39 UTC, merged

2016-12-18 12:09 UTC, ankitrgadiya commented on scripts/ImgChecker/ImgChecker.rb
> +blogsImgSize = 240
Thanks